# Generated by Django 3.1 on 2020-08-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200825_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commtent_date',
            new_name='comment_date',
        ),
    ]
